---
haproxy_config_path: "/etc/haproxy/haproxy.cfg"
masters: |
  {% for host in groups['masters'] %}
  {{ hostvars[host]['ip'] }}{% if not loop.last %},{% endif %}
  {% endfor %}

workers: |
  {% for host in groups['workers'] %}
  {{ hostvars[host]['ip'] }}{% if not loop.last %},{% endif %}
  {% endfor %}


k8s_masters: "{{ masters | trim | split(',') }}"
k8s_workers: "{{ workers | trim | split(',') }}"

enable_nginx_ingress: true
enable_oauth2_ingress: true

nginx_ingress:
  http_port: 46010
  https_port: 46011

oauth2_ingress:
  http_port: 46020
  https_port: 46021