---
platforms: 
  - name: instance-1
driver:
  name: default

provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory/hosts.yaml
      group_vars: inventory/group_vars
  playbooks:
    side_effect: side_effect/default.yaml
    

scenario:
  name: scale-cluster
  test_sequence:
    - create
    - converge
    - verify tests/test_cluster_healthy.yaml
    - side_effect side_effect/remove_control_plane.yaml
    - verify tests/test_scale_down.yaml
    - side_effect side_effect/add_control_plane.yaml
    - verify tests/test_scale_up.yaml
    - side_effect side_effect/remove_worker_node.yaml
    - verify tests/test_scale_down_worker.yaml
    - side_effect side_effect/add_worker_node.yaml
    - verify tests/test_scale_up_worker.yaml
    - destroy

verifier:
  name: ansible