#cloud-config
packages:
  - curl

ssh_pwauth: true
chpasswd:
  expire: false
users:
  - name: cluster
    groups: sudo
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF83HgxR5r+6noe2V3xTqvc6ArB0ERMIOZ3tXU7SLv2Q forswearbeetle@forswearbeetle-20jns4b400

    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
write_files:
  - content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    path: /etc/sysctl.d/k8s.conf
runcmd:
  - sudo sysctl --system