#cloud-config
packages_upgrade: true
packages:
  - curl

ssh_pwauth: true
chpasswd:
  expire: false
users:
  - name: haproxyadmin
    groups:
      - sudo
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEYRo0ugXsQ6XL7ZwzhbRMvgmiegIQbs64QNZm7Q1m7M forswearbeetle@forswearbeetle-20jns4b400

    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
write_files:
  - content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    path: /etc/sysctl.d/k8s.conf
runcmd:
  - sudo swapoff -a
  - sudo apt-get update
