---
- name: Create Hetzner VMs and Firewall
  hosts: localhost
  gather_facts: false
  vars:
    num_master_nodes: 1
    num_lb_nodes: 1
    num_worker_nodes: 1
    public_key: "{{ lookup('file', 'keys/k8s_cluster.pub') }}"

  tasks:
    - name: Create Hetzner Network
      hetzner.hcloud.network:
        name: abonded-network
        ip_range: "10.0.0.0/16"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      register: network

    - name: Create Hetzner Network Subnet
      hetzner.hcloud.subnetwork:
        network: abonded-network
        network_zone: "eu-central"
        ip_range: "10.0.0.0/24"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
        type: cloud
      register: subnet

    - name: Create Firewall
      hetzner.hcloud.firewall:
        name: my-firewall
        rules:
          - direction: in
            protocol: tcp
            port: "1-65535"
            source_ips:
              - "0.0.0.0/0"
              - "::/0"
          - direction: in
            protocol: udp
            port: "1-65535"
            source_ips:
              - "0.0.0.0/0"
              - "::/0"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      register: firewall

    - name: Create LoadBalancer Nodes
      hetzner.hcloud.server:
        name: "lb-node-{{ item + 1 }}"
        server_type: cpx31
        image: ubuntu-24.04
        location: "{{ lookup('env', 'HCLOUD_LOCATION') | default('fsn1') }}"
        enable_ipv4: true
        enable_ipv6: false
        firewalls:
          - my-firewall
        user_data: "{{ lookup('template', 'cloudinit/cloud-init-lb.yaml.j2')}}"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      loop: "{{ range(0, num_lb_nodes) | list }}"
      register: lb_nodes

    - name: Create Master Nodes
      hetzner.hcloud.server:
        name: "master-node-{{ item + 1 }}"
        server_type: cpx31
        image: ubuntu-24.04
        location: "{{ lookup('env', 'HCLOUD_LOCATION') | default('fsn1') }}"
        enable_ipv4: true
        enable_ipv6: false
        firewalls:
          - my-firewall
        user_data: "{{ lookup('template', 'cloudinit/cloud-init-master.yaml.j2')}}"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      loop: "{{ range(0, num_master_nodes) | list }}"
      register: master_nodes

    - name: Create Worker Nodes
      hetzner.hcloud.server:
        name: "worker-node-{{ item + 1 }}"
        server_type: cpx31
        image: ubuntu-24.04
        location: "{{ lookup('env', 'HCLOUD_LOCATION') | default('fsn1') }}"
        enable_ipv4: true
        enable_ipv6: false
        firewalls:
          - my-firewall
        user_data: "{{ lookup('template', 'cloudinit/cloud-init-worker.yaml.j2')}}"
        api_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
      loop: "{{ range(0, num_worker_nodes) | list }}"
      register: worker_nodes

    - name: Create a server network and specify the ip address
      hetzner.hcloud.server_network:
        network: abonded-network
        server: "lb-node-{{ item + 1 }}"
        ip: "10.0.0.1{{ item + 1 }}"
        state: present
      loop: "{{ range(0, num_lb_nodes) | list }}"

    - name: Create a server network and specify the ip address
      hetzner.hcloud.server_network:
        network: abonded-network
        server: "master-node-{{ item + 1 }}"
        ip: "10.0.0.2{{ item + 1 }}"
        state: present
      loop: "{{ range(0, num_master_nodes) | list }}"

    - name: Create a server network and specify the ip address
      hetzner.hcloud.server_network:
        network: abonded-network
        server: "worker-node-{{ item + 1 }}"
        ip: "10.0.0.3{{ item + 1 }}"
        state: present
      loop: "{{ range(0, num_worker_nodes) | list }}"

    - name: Store default inventory
      ansible.builtin.copy:
        content: |
          all:
            children:
              loadbalancer:
                hosts:
                  {% for node in lb_nodes.results -%}
                    lb-node-{{ node.item + 1 }}:
                      ansible_host: {{ node.hcloud_server.ipv4_address }}
                      ip: 10.0.0.1{{ node.item + 1 }}
                      ansible_user: haproxyadmin
                      ansible_ssh_private_key_file: keys/k8s_cluster
                  {% endfor +%}
              masters:
                hosts:
                  {% for node in master_nodes.results -%}
                    master-node-{{ node.item + 1 }}:
                      ansible_host: {{ node.hcloud_server.ipv4_address }}
                      ip: 10.0.0.2{{ node.item + 1 }}
                      ansible_user: cluster
                      ansible_ssh_private_key_file: keys/k8s_cluster
                      extra:
                        taints:
                          - node-role.kubernetes.io/control-plane:NoSchedule-
                  {% endfor +%}
              workers:
                hosts:
                  {% for node in worker_nodes.results -%}
                    worker-node-{{ node.item + 1 }}:
                      ansible_host: {{ node.hcloud_server.ipv4_address }}
                      ip: 10.0.0.3{{ node.item + 1 }}
                      ansible_user: cluster
                      ansible_ssh_private_key_file: keys/k8s_cluster
                      extra:
                        taints:
                          - node-role.kubernetes.io/control-plane:NoSchedule-
                  {% endfor +%}
        dest: "./inventory/hosts.yaml"
        mode: "0644"
