---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Enable and start HAProxy
  ansible.builtin.systemd_service:
    name: haproxy
    enabled: true
    state: restarted

- name: Generate HAProxy configuration for Oauth2 Ingress
  ansible.builtin.template:
    src: haproxy-for-oauth2-ingress.cfg.j2
    dest: "{{ haproxy_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart HAProxy


