---
- name: Lb for Control Plane
  ansible.builtin.import_tasks: configure_k8s_lb.yaml
  when:
    - inventory_hostname == groups['loadbalancer'][0]

- name: Lb for Ingress Cluster
  ansible.builtin.import_tasks: configure_nginx_ingress.yaml
  when:
    - enable_nginx_ingress
    - inventory_hostname == groups['loadbalancer'][1]

- name: Lb for Oauth2 Ingress
  ansible.builtin.import_tasks: configure_oauth2_ingress.yaml
  when:
    - enable_oauth2_ingress
    - inventory_hostname == groups['loadbalancer'][2]
