---
- name: Rotate Certs
  hosts: masters
  become: true
  tasks:
    - name: Add new host file
      ansible.builtin.include_role:
        name: master
        tasks_from: rotate-certs.yaml
      tags: rotate-certs
