- name: show upgrade plan
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubeadm upgrade plan --allow-release-candidate-upgrades > /opt/kubernetes/upgrade_plan.txt
  register: upgrade_plan
  tags: upgrade

# fetch the upgrade plan
- name: fetch the upgrade plan
  ansible.builtin.fetch:
    src: /opt/kubernetes/upgrade_plan.txt
    dest: /tmp/upgrade_plan.txt
    flat: yes
  tags: upgrade

# debug
- name: Upgrade Plan
  ansible.builtin.debug:
    msg:
    - "Have a look the upgrade plan in /tmp/upgrade_plan.txt"
  tags: upgrade
  

# debug
- name: Assure Message
  ansible.builtin.debug:
    msg:
    - "We're upgrading your cluster to the following kubernetes version {{ kubernetes_version }}"
  tags: upgrade

# upgrade nodes pacakages

- name: making the upgrade
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubeadm upgrade apply {{ kubernetes_version }} -y
  tags: upgrade

- name: Generate Kubeadm configuration
  ansible.builtin.template:
    src: "kubeadm-stacked-config.yaml.j2"
    dest: "{{ kubeadm_config_file }}"
    owner: root
    group: root
    mode: "0644"
  tags: init_kubeadm