# install local-path-provisioner
- name: Install local-path-provisioner
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml
    kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  args:
    creates: /opt/kubernetes/calico_installed
  tags: install_local-path-provisioner

# install metrics server

- name: Create metrics-server file
  ansible.builtin.template:
    src: metrics-server-values.yaml.j2
    dest: /opt/kubernetes/metrics-server-values.yaml
    mode: "0644"
  tags: install_metrics-server


- name: Deploy metrics-server with Helm
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server
    chart_version: 3.13.1
    chart_repo_url: https://kubernetes-sigs.github.io/metrics-server
    release_namespace: kube-system
    create_namespace: false
    values_files:
      - /opt/kubernetes/metrics-server-values.yaml
    kubeconfig: /etc/kubernetes/admin.conf
  tags: install_metrics-server