- name: Create calico.yaml file (default)
  ansible.builtin.template:
    src: calico.yaml.j2
    dest: /opt/kubernetes/calico.yaml
    mode: "0644"
  tags: install_calico

- name: Create calico.yaml file (with nodeAddressAutodetectionV4)
  ansible.builtin.template:
    src: calico-without-firstFound.yaml.j2
    dest: /opt/kubernetes/calico.yaml
    mode: "0644"
  when: calico_node_address_autodetection_v4 is defined and calico_node_address_autodetection_v4 | length > 0
  tags: install_calico


- name: Create calico global-network-policy.yaml file
  ansible.builtin.template:
    src: calico-global-network-policy.yaml.j2
    dest: /opt/kubernetes/calico-global-network-policy.yaml
    mode: "0644"
  tags: install_calico


- name: Deploy calico with Helm
  kubernetes.core.helm:
    name: calico
    chart_ref: tigera-operator
    chart_version: "{{ calico_chart_version }}"
    chart_repo_url: https://docs.tigera.io/calico/charts
    release_namespace: tigera-operator
    create_namespace: true
    values_files:
      - /opt/kubernetes/calico.yaml
    kubeconfig: /etc/kubernetes/admin.conf
  tags: install_calico


- name: Wait for tigera-operator pod to be ready
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl -n tigera-operator wait --for=condition=Ready pods --all --timeout=30s
  register: tigera_operator_ready
  until: tigera_operator_ready.rc == 0
  retries: 20
  delay: 30
  tags: install_calico
