- name: Prepare node
  ansible.builtin.import_tasks: prepare-nodes.yaml
  tags: prepare-nodes
  when:
    - inventory_hostname in nodes_to_add

- name: Copy join command
  ansible.builtin.import_tasks: copy-join-command.yaml
  when:
    - inventory_hostname == groups['masters'][0] or (inventory_hostname.startswith('master') and inventory_hostname in nodes_to_add)

- name: Reupload certs
  ansible.builtin.import_tasks: reupload-certs.yaml
  when:
    - inventory_hostname == groups['masters'][0]

- name: Reset Nodes
  ansible.builtin.import_tasks: reset-nodes.yaml
  when: inventory_hostname in nodes_to_add

- name: Join nodes
  ansible.builtin.import_tasks: join-nodes.yaml
  tags: join_nodes
  when:
    - inventory_hostname == groups['masters'][0] or (inventory_hostname.startswith('master') and inventory_hostname in nodes_to_add)

- name: Scale up worker nodes
  ansible.builtin.include_role:
    name: worker
  when:
    - inventory_hostname == groups['masters'][0] or (inventory_hostname in nodes_to_add and inventory_hostname.startswith('worker'))

- name: Copy calico hostendpoint config
  ansible.builtin.copy:
    src: "addons/calico-hostendpoint.yaml"
    dest: /opt/kubernetes/calico-hostendpoint.yaml
    mode: "0755"
  when: inventory_hostname == groups['masters'][0]
  tags: install_calico

- name: Apply Calico HostEndpoint manifest for each loadbalancer node
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    iface=$(ip -o link show | awk -F': ' '/altname public/ {print $2}')
    sed "s/node_name/{{ item }}/g; s/public/$iface/g" /opt/kubernetes/calico-hostendpoint.yaml | kubectl apply -f -
  vars:
    calico_hostendpoint_nodes: "{{ groups.get('workers', []) | select('match', '.*loadbalancer.*') | unique }}"
  loop: "{{ calico_hostendpoint_nodes }}"
  when: inventory_hostname == groups['masters'][0]
  tags: install_calico
