- name: Cordon Nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    echo "Cordon Node: {{ item }}"
    kubectl cordon {{ item }}
  with_items: "{{ nodes_to_remove | default([]) }}"
  when: nodes_to_remove | length > 0

- name: Drain Nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    echo "Drain Node: {{ item }}"
    kubectl drain {{ item }} --ignore-daemonsets  --delete-emptydir-data --grace-period=900
  with_items: "{{ nodes_to_remove | default([]) }}"
  when: nodes_to_remove | length > 0

- name: Delete Nodes
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    echo "Deleting Node: {{ item }}"
    kubectl delete node {{ item }} 
  with_items: "{{ nodes_to_remove | default([]) }}"
  when: nodes_to_remove | length > 0

- name: Remove etcd members only if it's control plane node
  ansible.builtin.shell: |
    export ETCDCTL_API=3
    ETCD_MEMBER_ID=$(etcdctl \
      --cacert=/etc/kubernetes/pki/etcd/ca.crt \
      --cert=/etc/kubernetes/pki/etcd/server.crt \
      --key=/etc/kubernetes/pki/etcd/server.key \
      member list | grep -P '(?<![\w-]){{ item }}(?![\w-])' | awk '{print $1}' | tr -d ',' )
    
    etcdctl  \
      --cacert=/etc/kubernetes/pki/etcd/ca.crt \
      --cert=/etc/kubernetes/pki/etcd/server.crt \
      --key=/etc/kubernetes/pki/etcd/server.key \
      member remove $ETCD_MEMBER_ID

  with_items: "{{ nodes_to_remove | default([]) }}"
  when: 
    - inventory_hostname == groups['masters'][0] and nodes_to_remove | length > 0
    - item is search("master-node-*")
  

- name: Reset the removed node
  ansible.builtin.command: kubeadm reset -f --cleanup-tmp-dir
  delegate_to: "{{ item }}"
  loop: "{{ nodes_to_remove }}"
  failed_when: false      # host may already be destroyed
  changed_when: true

- name: Stop and disable kubelet on the removed node
  ansible.builtin.systemd_service:
    name: kubelet
    state: stopped
    enabled: false
  delegate_to: "{{ item }}"
  loop: "{{ nodes_to_remove }}"
  failed_when: false