# upgrade nodes pacakages

- name: Upgrading {{ inventory_hostname }}
  ansible.builtin.shell: |
    kubeadm upgrade node
  tags: upgrade

- name: Generate Kubeadm configuration
  ansible.builtin.template:
    src: "kubeadm-stacked-config.yaml.j2"
    dest: "{{ kubeadm_config_file }}"
    owner: root
    group: root
    mode: "0644"
  tags: upgrade