---

- name: Prepare the node
  ansible.builtin.import_tasks: ../../common/tasks/prepare-node.yaml

- name: Install the worker storage dependencies
  ansible.builtin.apt:
    name: nfs-common
    state: present
