- name: Copy and rename a file
  hosts: localhost
  tasks:
    - name: Copy current host
      ansible.builtin.copy:
        src: ../inventory/hosts.yaml
        dest: ../inventory/hosts.old.yaml
        mode: "0644"
    - name: Add new host file
      ansible.builtin.copy:
        src: ../inventory/scale-down-ctrp.yaml
        dest: ../inventory/hosts.yaml
        mode: "0644"
        force: true

    - name: Refresh inventory to ensure new instances exist
      ansible.builtin.meta: refresh_inventory

- name: Sync Cluster
  ansible.builtin.import_playbook: ../../../playbooks/sync-resources.yaml